############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "People"
url = "people/"

[[main]]
name = "Research"
url = "research/"
weight = 3

[[main]]
name = "Publications"
url = "publications/"
weight = 4

[[main]]
weight = 5
name = "Facilities"
url = "facilities/"

[[main]]
weight = 6
name = "News"
url = "news/"





# [[main]]
# name = "About"
# url = "about/"
# weight = 7

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 8



# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
